name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set host directory permissions
      run: sudo chmod -R 777 $GITHUB_WORKSPACE

    # ==================================================
    #      RUN PLAYGROUND NOTEBOOKS WITH DOCKER
    # ==================================================
    - name: Build the Docker image
      run: |
        TAG=$(date +%s)
        echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
        docker build . --file .github/workflows/Dockerfile --tag my-image-name:$TAG
    - name: Run the Docker image
      run: |
        ABSOLUTE_PATH=$(pwd)
        WORK_PATH=$ABSOLUTE_PATH/PlaygroundMR0
        docker run -v $WORK_PATH:/usr/src/app:rw -u jovyan:users my-image-name:${{ env.IMAGE_TAG }}
    - name: Push changes
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Accessing the secret
      run: |
          git config --global user.email "magdamduarte@gmail.com"
          git config --global user.name "magdamd"
          git add .
          git commit -m "Automated commit"
          git push origin main

    # ==================================================
    #      COMPARISON GROUND TRUTH - LAST PUSH
    # ==================================================
    
    #- name: Set up Python
    #  uses: actions/setup-python@v4
    #  with:
    #    python-version: '3.10'  # Replace with your desired Python version

    #- name: Install dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install flake8 pytest
    #    pip install -r .github/workflows/requirements_PlaygroundMR0_pytest.txt

    #- name: Run specific test
    #  run: |
    #    pytest ./PlaygroundMR0/Comparison_results_workflow.py
